### ISSUE TITLE
Setup programming to read-in and process building permit data

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/DCRA#1]
Step 1. program/macros to read-in data
Step 2. program/macros to clean data
Step 3. program/macros to create summary data for DC geographies

**Comment by rpitingolo** [comment]
@maggiesu0725 here is the list of tasks you can work on tomorrow. I can review on Monday morning when I am back in the office. 

- [x] Create a dummy variable for all permits
- [x] Create dummy variables permit type from variable PERMIT_TYP
- [x] Append _yyyy to each new dummy variable
- [x] Use proc summary and a macro to create a dataset for each standard geography in a given year. 
- [x] Add a finalize data macro to the end of the program

**Comment by maggiesu0725** [comment]
@rpitingolo I think you opened a branch but didn't publish or commit to the branch? can't see your programs.

**Comment by rpitingolo** [comment]
Closing this issue. There is a problem with the formats (that doesn't prevent the files from being created) but I will open a new bugfix issue to address.
